# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@1.0.6

jobs:
  backend_build_and_test:
    executor: node/default
    working_directory: ~/resolution
    steps:
      # get code from repo
      - checkout
      # install node@18.10.0
      - node/install:
          node-version: 18.10.0
      # install the npm packages for server
      - node/install-packages:
          app-dir: ~/resolution/server
          cache-path: node_modules
          override-ci-command: npm i
      # build the server
      - run:
          name: "Build the server"
          command: cd server && npm run build
      # run the test suites
      - run:
          name: "Run jest and collect coverage reports"
          command: cd server && npm test
      # upload coverage results to coveralls **using `npx coveralls`***
      # (the orb doesn't seem to be working for me)
      - run:
          name: "Upload coverage results to coveralls"
          command: cat ~/resolution/server/coverage/lcov.info | npx coveralls --verbose ~/resolution/server

  frontend_build_and_test:
    executor: node/default
    working_directory: ~/resolution
    steps:
      - checkout
      - node/install:
          node-version: 18.10.0
      - node/install-packages:
          app-dir: ~/resolution/client
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: "Build the React application"
          command: cd client && npm run build
      # we would test here
      - persist_to_workspace:
          root: ~/resolution/client
          paths: [build]

  frontend_deploy:
    executor: node/default
    working_directory: ~/resolution
    steps:
      - checkout
      - attach_workspace:
          at: ~/resolution/client
      - run:
          name: "Install and configure gh-pages package"
          command: |
            npm install gh-pages
            git config user.name "mitchellnel"
            git config user.email "mitchellmclin@gmail.com"
      - run:
          name: "Deploy React application to gh-pages branch"
          command: gh-pages --dist ~/resolution/client/build

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  backend_ci:
    jobs:
      - backend_build_and_test
  frontend_ci_cd:
    jobs:
      - frontend_build_and_test
      - frontend_deploy:
          requires:
            - frontend_build_and_test
          filters:
            branches:
              only:
                - main
