const API_CREATE_RESOLUTION_ENDPOINT = "/api/create-resolution";
const API_READ_RESOLUTION_ENDPOINT = "/api/read-resolution";
const API_UPDATE_RESOLUTION_ENDPOINT = "/api/update-resolution";
const API_DELETE_RESOLUTION_ENDPOINT = "/api/delete-resolution";

export {
  API_CREATE_RESOLUTION_ENDPOINT,
  API_READ_RESOLUTION_ENDPOINT,
  API_UPDATE_RESOLUTION_ENDPOINT,
  API_DELETE_RESOLUTION_ENDPOINT,
};
