const API_CREATE_RESOLUTION_ENDPOINT = "/api/create-resolution";
const API_READ_RESOLUTION_ENDPOINT = "/api/read-resolution";
const API_UPDATE_RESOLUTION_ENDPOINT = "/api/update-resolution";
const API_DELETE_RESOLUTION_ENDPOINT = "/api/delete-resolution";

const API_CREATE_GOAL_ENDPOINT = "/api/create-goal";
const API_READ_GOAL_ENDPOINT = "/api/read-goal";
const API_UPDATE_GOAL_ENDPOINT = "/api/update-goal";
const API_DELETE_GOAL_ENDPOINT = "/api/delete-goal";

export {
  API_CREATE_RESOLUTION_ENDPOINT,
  API_READ_RESOLUTION_ENDPOINT,
  API_UPDATE_RESOLUTION_ENDPOINT,
  API_DELETE_RESOLUTION_ENDPOINT,
  API_CREATE_GOAL_ENDPOINT,
  API_READ_GOAL_ENDPOINT,
  API_UPDATE_GOAL_ENDPOINT,
  API_DELETE_GOAL_ENDPOINT,
};
